language: node_js
node_js:
  - "lts/*"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./dist
  on:
    branch: master
cache:
  yarn: true
  directories:
    - "node_modules"
notifications:
  email:
    on_success: never
    on_failure: always

